# Generated by Django 5.2.8 on 2026-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_student_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_stop',
            field=models.IntegerField(blank=True, null=True, db_column='bus_stop_id'),
        ),
    ]
