# Generated by Django 5.2.11 on 2026-09-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_examsubjectmaxmark_pass_marks_markentry_pass_marks_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS students_student_bus_stop_id_372cd484;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='suspend_student_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='advance_balance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bus_stop',
        ),
    ]
