# Generated by Django 5.2.4 on 2026-09-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_remove_globalsettings_suspend_student_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='day_of_week',
            field=models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=15),
        ),
    ]
